// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// UserController is an autogenerated mock type for the UserController type
type UserController struct {
	mock.Mock
}

// Login provides a mock function with given fields: c
func (_m *UserController) Login(c *gin.Context) {
	_m.Called(c)
}

// Register provides a mock function with given fields: c
func (_m *UserController) Register(c *gin.Context) {
	_m.Called(c)
}
