// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// Routes is an autogenerated mock type for the Routes type
type Routes struct {
	mock.Mock
}

// RouteGroups provides a mock function with given fields: route
func (_m *Routes) RouteGroups(route *gin.Engine) {
	_m.Called(route)
}

// authRoutes provides a mock function with given fields: route
func (_m *Routes) authRoutes(route *gin.Engine) {
	_m.Called(route)
}

// noAuthRoutes provides a mock function with given fields: route
func (_m *Routes) noAuthRoutes(route *gin.Engine) {
	_m.Called(route)
}
